"""freeze weekly score on commitment

Revision ID: 312843ad930e
Revises: df3ac082e4d3
Create Date: 2026-08-28 00:41:28.179656
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '312843ad930e'
down_revision: str | None = 'df3ac082e4d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_commitment', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('weekly_commitment', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_commitment', 'score_breakdown')
    op.drop_column('weekly_commitment', 'score')
    # ### end Alembic commands ###
