"""v0 schema

Revision ID: 7cee8255ae1c
Revises: 
Create Date: 2026-08-28 00:28:39.768793
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from alembic import op

from goalos.api.db import COMPLETED_UNITS_TRIGGER, DROP_COMPLETED_UNITS_TRIGGER

revision: str = '7cee8255ae1c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('available_hours', sa.Float(), nullable=False),
    sa.Column('session_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capacity_week_start'), 'capacity', ['week_start'], unique=True)
    op.create_table('daily_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('capacity_minutes', sa.Integer(), nullable=False),
    sa.Column('carried_shortfall', sa.Float(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_plan_plan_date'), 'daily_plan', ['plan_date'], unique=True)
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_of_done', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dod_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('pace_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reset_period_days', sa.Integer(), nullable=True),
    sa.Column('stakes', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("activation IN ('active', 'parked')", name='goal_activation_valid'),
    sa.CheckConstraint("dod_source IN ('user_supplied', 'model_estimated')", name='goal_dod_source_valid'),
    sa.CheckConstraint("kind = 'vision' OR activation <> 'active' OR deadline IS NOT NULL", name='goal_active_requires_deadline'),
    sa.CheckConstraint("kind IN ('vision', 'goal')", name='goal_kind_valid'),
    sa.CheckConstraint("pace_mode <> 'reset_period' OR reset_period_days IS NOT NULL", name='goal_reset_period_requires_days'),
    sa.CheckConstraint("pace_mode IN ('carry_forward', 'reset_period')", name='goal_pace_mode_valid'),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'done', 'abandoned')", name='goal_status_valid'),
    sa.CheckConstraint('length(trim(definition_of_done)) > 0', name='goal_dod_not_blank'),
    sa.CheckConstraint('stakes BETWEEN 1 AND 5', name='goal_stakes_range'),
    sa.ForeignKeyConstraint(['parent_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_parent_id'), 'goal', ['parent_id'], unique=False)
    op.create_table('goal_budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('budgeted_sessions', sa.Integer(), nullable=False),
    sa.CheckConstraint('budgeted_sessions >= 0', name='goal_budget_non_negative'),
    sa.ForeignKeyConstraint(['capacity_id'], ['capacity.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capacity_id', 'goal_id', name='goal_budget_unique')
    )
    op.create_index(op.f('ix_goal_budget_capacity_id'), 'goal_budget', ['capacity_id'], unique=False)
    op.create_index(op.f('ix_goal_budget_goal_id'), 'goal_budget', ['goal_id'], unique=False)
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_of_done', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dod_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('planned_sessions', sa.Integer(), nullable=True),
    sa.Column('exploratory', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("dod_source IN ('user_supplied', 'model_estimated')", name='milestone_dod_source_valid'),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'done', 'abandoned')", name='milestone_status_valid'),
    sa.CheckConstraint('blocked_by IS NULL OR blocked_by <> id', name='milestone_no_self_block'),
    sa.CheckConstraint('length(trim(definition_of_done)) > 0', name='milestone_dod_not_blank'),
    sa.ForeignKeyConstraint(['blocked_by'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestone_goal_id'), 'milestone', ['goal_id'], unique=False)
    op.create_table('trackable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_units', sa.Float(), nullable=False),
    sa.Column('total_units_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_units', sa.Float(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('prior_pace', sa.Float(), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exploratory', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'done', 'abandoned')", name='trackable_status_valid'),
    sa.CheckConstraint("task_type IN ('reading', 'problems', 'writing', 'exploratory', 'admin')", name='trackable_task_type_valid'),
    sa.CheckConstraint("total_units_source IN ('grounded', 'user_supplied', 'model_estimated')", name='trackable_units_source_valid'),
    sa.CheckConstraint('completed_units >= 0', name='trackable_completed_non_negative'),
    sa.CheckConstraint('total_units > 0', name='trackable_total_units_positive'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackable_milestone_id'), 'trackable', ['milestone_id'], unique=False)
    op.create_table('baseline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trackable_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('planned_sessions', sa.Integer(), nullable=False),
    sa.Column('scope_units', sa.Float(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("resolution IS NULL OR resolution IN ('add_sessions', 'cut_scope', 'move_deadline', 'declare_infeasible')", name='baseline_resolution_valid'),
    sa.CheckConstraint('(trackable_id IS NOT NULL) <> (milestone_id IS NOT NULL)', name='baseline_exactly_one_target'),
    sa.CheckConstraint('version = 1 OR (resolution IS NOT NULL AND rationale IS NOT NULL)', name='baseline_rebaseline_requires_reason'),
    sa.CheckConstraint('version >= 1', name='baseline_version_positive'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('baseline_milestone_version_unique', 'baseline', ['milestone_id', 'version'], unique=True, postgresql_where=sa.text('milestone_id IS NOT NULL'))
    op.create_index('baseline_trackable_version_unique', 'baseline', ['trackable_id', 'version'], unique=True, postgresql_where=sa.text('trackable_id IS NOT NULL'))
    op.create_index(op.f('ix_baseline_milestone_id'), 'baseline', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_baseline_trackable_id'), 'baseline', ['trackable_id'], unique=False)
    op.create_table('open_gap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('trackable_id', sa.Integer(), nullable=True),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'answered', 'dismissed')", name='open_gap_status_valid'),
    sa.CheckConstraint('goal_id IS NOT NULL OR milestone_id IS NOT NULL OR trackable_id IS NOT NULL', name='open_gap_has_a_subject'),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_gap_goal_id'), 'open_gap', ['goal_id'], unique=False)
    op.create_index(op.f('ix_open_gap_milestone_id'), 'open_gap', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_open_gap_trackable_id'), 'open_gap', ['trackable_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('trackable_id', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('expected_output', sa.Float(), nullable=True),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('open', 'done', 'deferred', 'dropped')", name='task_status_valid'),
    sa.CheckConstraint('blocked_by IS NULL OR blocked_by <> id', name='task_no_self_block'),
    sa.ForeignKeyConstraint(['blocked_by'], ['task.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_milestone_id'), 'task', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_task_trackable_id'), 'task', ['trackable_id'], unique=False)
    op.create_table('weekly_commitment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity_id', sa.Integer(), nullable=False),
    sa.Column('trackable_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('committed_sessions', sa.Integer(), nullable=False),
    sa.Column('target_units', sa.Float(), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(trackable_id IS NOT NULL) <> (milestone_id IS NOT NULL)', name='weekly_commitment_exactly_one_target'),
    sa.CheckConstraint('committed_sessions >= 0', name='weekly_commitment_non_negative'),
    sa.ForeignKeyConstraint(['capacity_id'], ['capacity.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_commitment_capacity_id'), 'weekly_commitment', ['capacity_id'], unique=False)
    op.create_index('weekly_commitment_milestone_unique', 'weekly_commitment', ['capacity_id', 'milestone_id'], unique=True, postgresql_where=sa.text('milestone_id IS NOT NULL'))
    op.create_index('weekly_commitment_trackable_unique', 'weekly_commitment', ['capacity_id', 'trackable_id'], unique=True, postgresql_where=sa.text('trackable_id IS NOT NULL'))
    op.create_table('plan_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('daily_plan_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('trackable_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('allocated_units', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('user_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("score_breakdown::text <> '{}'", name='plan_item_breakdown_not_empty'),
    sa.CheckConstraint("tier IN ('A', 'B', 'C', 'D')", name='plan_item_tier_valid'),
    sa.CheckConstraint("user_action IS NULL OR user_action IN ('accepted', 'modified', 'rejected', 'deferred')", name='plan_item_user_action_valid'),
    sa.CheckConstraint('(trackable_id IS NOT NULL) <> (milestone_id IS NOT NULL)', name='plan_item_exactly_one_target'),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plan.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_item_daily_plan_id'), 'plan_item', ['daily_plan_id'], unique=False)
    op.create_table('work_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('trackable_id', sa.Integer(), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=False),
    sa.Column('actual_minutes', sa.Float(), nullable=True),
    sa.Column('expected_output', sa.Float(), nullable=True),
    sa.Column('actual_output', sa.Float(), nullable=True),
    sa.Column('intent_met', sa.Boolean(), nullable=True),
    sa.Column('focus_rating', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interrupted', sa.Boolean(), nullable=False),
    sa.Column('entered_retroactively', sa.Boolean(), nullable=False),
    sa.CheckConstraint("task_type IN ('reading', 'problems', 'writing', 'exploratory', 'admin')", name='work_session_task_type_valid'),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name='work_session_ends_after_start'),
    sa.CheckConstraint('planned_minutes > 0', name='work_session_planned_minutes_positive'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_session_milestone_id'), 'work_session', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_work_session_trackable_id'), 'work_session', ['trackable_id'], unique=False)
    op.create_index('work_session_task_type_started', 'work_session', ['task_type', 'started_at'], unique=False)
    op.create_table('progress_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('trackable_id', sa.Integer(), nullable=True),
    sa.Column('self_assessed_pct', sa.Float(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('(trackable_id IS NOT NULL) <> (milestone_id IS NOT NULL)', name='progress_check_exactly_one_target'),
    sa.CheckConstraint('self_assessed_pct >= 0 AND self_assessed_pct <= 100', name='progress_check_pct_range'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['work_session.id'], ),
    sa.ForeignKeyConstraint(['trackable_id'], ['trackable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_check_milestone_id'), 'progress_check', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_progress_check_trackable_id'), 'progress_check', ['trackable_id'], unique=False)
    # ### end Alembic commands ###


    # trackable.completed_units is a cache of SUM(actual_output) (§21). A trigger
    # keeps it correct no matter which write path touches a session, so AC7's
    # invariant cannot be broken by forgetting to recompute in application code.
    op.execute(COMPLETED_UNITS_TRIGGER)


def downgrade() -> None:
    op.execute(DROP_COMPLETED_UNITS_TRIGGER)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_check_trackable_id'), table_name='progress_check')
    op.drop_index(op.f('ix_progress_check_milestone_id'), table_name='progress_check')
    op.drop_table('progress_check')
    op.drop_index('work_session_task_type_started', table_name='work_session')
    op.drop_index(op.f('ix_work_session_trackable_id'), table_name='work_session')
    op.drop_index(op.f('ix_work_session_milestone_id'), table_name='work_session')
    op.drop_table('work_session')
    op.drop_index(op.f('ix_plan_item_daily_plan_id'), table_name='plan_item')
    op.drop_table('plan_item')
    op.drop_index('weekly_commitment_trackable_unique', table_name='weekly_commitment', postgresql_where=sa.text('trackable_id IS NOT NULL'))
    op.drop_index('weekly_commitment_milestone_unique', table_name='weekly_commitment', postgresql_where=sa.text('milestone_id IS NOT NULL'))
    op.drop_index(op.f('ix_weekly_commitment_capacity_id'), table_name='weekly_commitment')
    op.drop_table('weekly_commitment')
    op.drop_index(op.f('ix_task_trackable_id'), table_name='task')
    op.drop_index(op.f('ix_task_milestone_id'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_open_gap_trackable_id'), table_name='open_gap')
    op.drop_index(op.f('ix_open_gap_milestone_id'), table_name='open_gap')
    op.drop_index(op.f('ix_open_gap_goal_id'), table_name='open_gap')
    op.drop_table('open_gap')
    op.drop_index(op.f('ix_baseline_trackable_id'), table_name='baseline')
    op.drop_index(op.f('ix_baseline_milestone_id'), table_name='baseline')
    op.drop_index('baseline_trackable_version_unique', table_name='baseline', postgresql_where=sa.text('trackable_id IS NOT NULL'))
    op.drop_index('baseline_milestone_version_unique', table_name='baseline', postgresql_where=sa.text('milestone_id IS NOT NULL'))
    op.drop_table('baseline')
    op.drop_index(op.f('ix_trackable_milestone_id'), table_name='trackable')
    op.drop_table('trackable')
    op.drop_index(op.f('ix_milestone_goal_id'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_goal_budget_goal_id'), table_name='goal_budget')
    op.drop_index(op.f('ix_goal_budget_capacity_id'), table_name='goal_budget')
    op.drop_table('goal_budget')
    op.drop_index(op.f('ix_goal_parent_id'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_daily_plan_plan_date'), table_name='daily_plan')
    op.drop_table('daily_plan')
    op.drop_index(op.f('ix_capacity_week_start'), table_name='capacity')
    op.drop_table('capacity')
    # ### end Alembic commands ###
